### ISSUE TITLE
Support for redis oplog

### ISSUE THREAD

**Issue by emenoh** [zodern/mup-redis#1]
Using a redis oplog rather than Mongo oplog is becoming a popular option.

https://github.com/cult-of-coders/redis-oplog

It's not clear if such a use case would work with this. Does the --append-only flag interfere? Currently I'm using a separate redis docker image for this. Any thoughts?

**Comment by zodern** [comment]
Currently, this plugin only supports the Meteor app running on one server. After Meteor Up 1.5, I will add support for using mup-redis when running an app on multiple servers, and look into if any changes need to be made to support redis-oplog.

**Comment by pagesrichie** [comment]
Will this work with https://github.com/zodern/mup-aws-beanstalk and/or will there be a redis option over there?  Love your mup-aws-beanstalk!!

**Comment by edemaine** [comment]
I'm looking to switch my applications to redis-oplog, so came across this discussion again. The [how it works](https://github.com/cult-of-coders/redis-oplog/blob/master/docs/how_it_works.md) document says "We don't use Redis as a database, we do not store anything in it." which suggests we really don't want Redis persistence turned on.

Could we make the persistence mode configurable in this plugin? Or perhaps it doesn't matter, if nothing is actually getting written to the database?

**Comment by edemaine** [comment]
FWIW, I just got Redis Oplog (with Redos 6.0.8-alpine) working fine with this plugin (with Meteor, Mongo, Redis all running on the same machine). I just needed the following to `settings.json`:

```json
{
  "redisOplog": {
    "redis": {
      "host": "redis",
      "port": 6379
    }
  }
}
```

(The default hostname otherwise is `127.0.0.1` which doesn't work because of Docker.)  Perhaps worth adding to the README? I can write a PR.

> Could we make the persistence mode configurable in this plugin? Or perhaps it doesn't matter, if nothing is actually getting written to the database?

After many pub/sub events, I can confirm that `/opt/redis/data/appendonly.aof` is 0 bytes, so I don't think this library needs any changes (and perhaps this issue should be closed?).
